#!/usr/bin/env python3
"""Rebuild assets/icons/phosphor.{css,woff2}: the Phosphor icons (regular weight)
that the site actually uses, instead of loading the whole icon set from a CDN.

Run it again after adding a new <i class="ph ph-..."> anywhere on the site:

    npm pack @phosphor-icons/web@2.1.2 && tar xzf phosphor-icons-web-2.1.2.tgz
    pip install fonttools brotli
    python3 tools/build-icons.py package/src/regular
"""
import pathlib, re, subprocess, sys

root = pathlib.Path(__file__).resolve().parent.parent
src = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else 'package/src/regular')
css = (src / 'style.css').read_text()

used = set()
for f in root.rglob('*'):
    if f.suffix in ('.html', '.js') and '.git' not in f.parts and 'tools' not in f.parts:
        used |= set(re.findall(r'\bph-[a-z0-9-]+', f.read_text(errors='ignore')))

rules = dict(re.findall(r'\.(ph-[a-z0-9-]+):before\s*\{\s*content:\s*"\\([0-9a-f]+)";\s*\}', css))
missing = sorted(used - rules.keys())
if missing:
    sys.exit('unknown icons: ' + ', '.join(missing))
names = sorted(used)
codes = sorted({rules[n] for n in names})

out = root / 'assets/icons'
out.mkdir(parents=True, exist_ok=True)
subprocess.run(['pyftsubset', str(src / 'Phosphor.ttf'), '--unicodes=' + ','.join('U+' + c for c in codes),
                '--flavor=woff2', '--layout-features=', '--no-hinting', '--desubroutinize',
                '--output-file=' + str(out / 'phosphor.woff2')], check=True)

base = re.search(r'\.ph \{.*?\n\}', css, re.S).group(0)
body = ['/* Generated by tools/build-icons.py: Phosphor Icons (MIT), regular weight, only the icons used on the site. */',
        '@font-face{font-family:"Phosphor";src:url("phosphor.woff2") format("woff2");font-weight:normal;font-style:normal;font-display:block}',
        base]
body += [f'.ph.{n}:before{{content:"\\{rules[n]}"}}' for n in names]
(out / 'phosphor.css').write_text('\n'.join(body) + '\n')
print(f'{len(names)} icons, {len(codes)} glyphs -> {out}')
