#!/usr/bin/env python3
"""Rebuild assets/fonts/: the site's Google Fonts, self-hosted.

Downloads the variable versions of Unbounded, JetBrains Mono and Manrope
(one file per alphabet covers every weight) and writes assets/fonts/fonts.css
with the same unicode-range split Google uses, so a page only downloads the
alphabets it shows.

    python3 tools/build-fonts.py
"""
import pathlib, re, urllib.request

FAMILIES = 'family=JetBrains+Mono:wght@100..800&family=Manrope:wght@200..800&family=Unbounded:wght@200..900'
UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0 Safari/537.36'
out = pathlib.Path(__file__).resolve().parent.parent / 'assets/fonts'
out.mkdir(parents=True, exist_ok=True)

def get(url):
    return urllib.request.urlopen(urllib.request.Request(url, headers={'User-Agent': UA})).read()

css = get(f'https://fonts.googleapis.com/css2?{FAMILIES}&display=swap').decode()
rules = ['/* Generated by tools/build-fonts.py from Google Fonts (SIL Open Font License). */']
for subset, body in re.findall(r'/\* ([a-z-]+) \*/\s*@font-face \{(.*?)\}', css, re.S):
    family = re.search(r"font-family: '([^']+)'", body).group(1)
    url = re.search(r'url\((https://[^)]+)\)', body).group(1)
    name = f"{family.lower().replace(' ', '-')}-{subset}.woff2"
    (out / name).write_bytes(get(url))
    body = body.replace(url, name)
    rules.append('@font-face {' + re.sub(r'\s+', ' ', body).strip() + '}')
(out / 'fonts.css').write_text('\n'.join(rules) + '\n')
print(f'{len(rules) - 1} font files -> {out}')
